FROM node:20-alpine

## To run this Docker container:
## docker build . -t yarntest && docker run --rm -it yarntest


## Run the next line for success (using yarn 1.22.19)
## RUN npm i -g yarn@1.22.19 -f
## Run the next line for failure (using yarn 1.22.20)
RUN npm i -g yarn@1.22.20 -f


WORKDIR /usr/src
RUN echo '{ "packageManager": "yarn@3.4.1", "scripts": { "test": "echo hi" } }' > package.json
RUN yarn test
## ENTRYPOINT /bin/sh
